// src/Formulus.tsx
import { Field, Form, Formik, FormikHelpers, FormikProps, FormikValues } from 'formik';
import { FormulusSchema } from './FormulusSchema';
import { FormulusColumn } from './FormulusColumn';
import OneDefault from './ornaments/one-default';
import OneSuccess from './ornaments/one-success';
import OneError from './ornaments/one-error';
import { useState } from 'react';
import { ThreeDefault } from './ornaments/three-default';
import { ThreeError } from './ornaments/three-error';
import { ThreeSuccess } from './ornaments/three-success';
import { TwoDefault } from './ornaments/two-default';
import { TwoError } from './ornaments/two-error';
import { TwoSuccess } from './ornaments/two-success';
import { FourDefault } from './ornaments/four-default';
import { FourError } from './ornaments/four-error';
import { FourSuccess } from './ornaments/four-success';
import { FiveDefault } from './ornaments/five-default';
import { FiveError } from './ornaments/five-error';
import { FiveSuccess } from './ornaments/five-success';

interface FormValues {
    type: string;
    input: string;
}

export const Formulus = () => {
    const [isValid, setIsValid] = useState(false);
    const [validating, setValidating] = useState(false);

    const handleValidation = (validateForm: FormikProps<FormikValues>['validateForm']) => {
        setValidating(true);
        validateForm().then((formErrors: any) => {
            setIsValid(Object.keys(formErrors).length === 0);
            setTimeout(() => {
                setValidating(false);
                setTimeout(() => {
                    setValidating(true);
                }, 100);
            }, 100);
        });
    };

    return (
        <Formik
            initialValues={{
                type: 'email',
                input: '',
            }}
            onSubmit={(values: FormValues, { setSubmitting }: FormikHelpers<FormValues>) => {
                console.log(values);
                setSubmitting(false);
            }}
            validationSchema={FormulusSchema}
            validateOnChange={false}
            validateOnBlur={false}
        >
        {({ errors, validateForm, values }) => (
            <Form className="border-b border-slate-400 grow gap-12 mb-3 mt-12 w-full">
                <div className="flex flex-wrap gap-6 justify-around h-full content-end mx-auto px-12">
                    <div className="flex flex-col px-3">
                        <div className="border border-slate-300 p-2 rounded dark:border-slate-500">
                            <label className="block mb-2" htmlFor="type">Type</label>
                            <Field className="border border-slate-400 p-1 dark:border-slate-500" as="select" id="type" name="type">
                                <option value="email">Email</option>
                                <option value="tel">Phone</option>
                                <option value="number">Number</option>
                            </Field>
                        </div>
                        <FormulusColumn key={validating.toString()} validating={validating}>
                            <div className="content-between grid grid-cols-5 grid-rows-1 h-full">
                                <div className="col-start-1 col-end-4">
                                    {!values.input ? <TwoDefault /> : Object.keys(errors).length > 0 && !isValid ? <TwoError /> : isValid ? <TwoSuccess /> : <TwoDefault />}
                                </div>
                                <div className="col-start-2 col-end-5 h-[70%] self-end">
                                    {!values.input ? <ThreeDefault /> : Object.keys(errors).length > 0 && !isValid ? <ThreeError /> : isValid ? <ThreeSuccess /> : <ThreeDefault />}                                
                                </div>
                            </div>
                        </FormulusColumn>
                    </div>
                    <div className="flex flex-col basis-3/6 px-3 relative">
                        <div className="border border-slate-400 p-2 rounded dark:border-slate-500">
                            <label className="block mb-2" htmlFor={values.type}>Input</label>
                            <Field
                                className="border border-slate-400 p-1 w-100"
                                id="input"
                                name="input"
                                type={values.type}
                            />
                            {errors[values.type as keyof typeof errors] && <div>{errors[values.type as keyof typeof errors]}</div>}
                        </div>
                        <FormulusColumn key={validating.toString()} validating={validating}>
                            <div className="content-between grid grid-cols-6 grid-rows-2 h-full max-h-[60vh]">
                                <div className="col-start-1 col-span-4 max-h-[300px]">
                                    {!values.input ? <FourDefault /> : Object.keys(errors).length > 0 && !isValid ? <FourError /> : isValid ? <FourSuccess /> : <FourDefault />}
                                </div>
                                <div className="col-start-1 col-end-4 self-end">
                                    {!values.input ? <OneDefault /> : Object.keys(errors).length > 0 && !isValid ? <OneError /> : isValid ? <OneSuccess /> : <OneDefault />}
                                </div>
                                <div className="col-end-7 col-span-2">
                                    {!values.input ? <FiveDefault /> : Object.keys(errors).length > 0 && !isValid ? <FiveError /> : isValid ? <FiveSuccess /> : <FiveDefault />}
                                </div>
                            </div>
                        </FormulusColumn>
                    </div>
                    <div className="self-end">
                        <div className="border border-slate-400 p-2 rounded dark:border-slate-500">
                            <button
                                className="border border-slate-400"
                                onClick={() => handleValidation(validateForm)}
                                type="button"
                            >Validate</button>
                        </div>
                        <FormulusColumn key={validating.toString()} validating={validating}></FormulusColumn>
                    </div>
                </div>
            </Form>
        )}
        </Formik>
    )
};

// src/Formulus.svelte
<script lang="ts">
  import FormulusColumn from './FormulusColumn.svelte';
  import FiveDefault from './ornaments/five-default.svelte';
  import FiveError from './ornaments/five-error.svelte';
  import FiveSuccess from './ornaments/five-success.svelte';
  import FourDefault from './ornaments/four-default.svelte';
  import FourError from './ornaments/four-error.svelte';
  import FourSuccess from './ornaments/four-success.svelte';
  import OneDefault from './ornaments/one-default.svelte';
  import OneError from './ornaments/one-error.svelte';
  import OneSuccess from './ornaments/one-success.svelte';
  import ThreeDefault from './ornaments/three-default.svelte';
  import ThreeError from './ornaments/three-error.svelte';
  import ThreeSuccess from './ornaments/three-success.svelte';
  import TwoDefault from './ornaments/two-default.svelte';
  import TwoError from './ornaments/two-error.svelte';
  import TwoSuccess from './ornaments/two-success.svelte';


    type InputType = 'email' | 'tel' | 'number';

    let type = $state<InputType>('email');
    let input = $state<string>('');
    let validating = $state(false);


    let validated = $state(false);
    let isValid = $state(false);

    function computeIsValid(t: InputType, value: string) {
        const v = value.trim();
        if (!v) return false;

        if (t === 'email') {
            // simple email check
            return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(v);
        }

        if (t === 'tel') {
            // simple phone check (digits + basic symbols)
            return /^[+()\-\s0-9]{7,}$/.test(v);
        }

        // t === 'number'
        const n = Number(v);
        return Number.isFinite(n);
    }

    async function handleValidation() {
        validating = true;

        await Promise.resolve();

        validated = true;
        isValid = computeIsValid(type, input);

        validating = false;
    }
</script>

<div class="content-end gap-7 grid grid-cols-[repeat(auto-fit,minmax(300px,1fr))] items-end mx-auto px-12 w-full">
    <div class="flex flex-col h-full px-3">
        <div class="border border-slate-400 p-7 rounded dark:border-slate-500">
            <label class="block mb-2" for="type">Type</label>
            <select
                class="border border-slate-400 p-1 dark:border-slate-500"
                id="type"
                name="type"
                bind:value={type}
            >
                <option value="email">Email</option>
                <option value="tel">Phone</option>
                <option value="number">Number</option>
            </select>
        </div>

        {#key validating}
            <FormulusColumn {validating}>
                <div class="content-between grid grid-cols-5 grid-rows-1 h-full">
                    <div class="col-start-1 col-end-4">
                        {#if !validated}
                            <TwoDefault />
                        {:else if isValid}
                            <TwoSuccess />
                        {:else}
                            <TwoError />
                        {/if}
                    </div>

                    <div class="col-start-2 col-end-5 h-[70%] self-end">
                        {#if !validated}
                            <ThreeDefault />
                        {:else if isValid}
                            <ThreeSuccess />
                        {:else}
                            <ThreeError />
                        {/if}
                    </div>
                </div>
            </FormulusColumn>
        {/key}
    </div>

    <div class="flex flex-col h-full px-3">
        <div class="border border-slate-400 p-7 rounded dark:border-slate-500">
            <label class="block mb-2" for="input">Input</label>
            <input
                class="border border-slate-400 p-1 w-full"
                id="input"
                name="input"
                type={type}
                bind:value={input}
            />
        </div>

        {#key validating}
            <FormulusColumn {validating}>
                <div class="content-between grid grid-cols-6 grid-rows-2 h-full">
                    <div class="col-start-1 col-span-4 max-h-[300px]">
                        {#if !validated}
                            <FourDefault />
                        {:else if isValid}
                            <FourSuccess />
                        {:else}
                            <FourError />
                        {/if}
                    </div>

                    <div class="col-start-1 col-end-4 self-end">
                        {#if !validated}
                            <OneDefault />
                        {:else if isValid}
                            <OneSuccess />
                        {:else}
                            <OneError />
                        {/if}
                    </div>

                    <div class="col-end-7 col-span-2">
                        {#if !validated}
                            <FiveDefault />
                        {:else if isValid}
                            <FiveSuccess />
                        {:else}
                            <FiveError />
                        {/if}
                    </div>
                </div>
            </FormulusColumn>
        {/key}
    </div>

    <div class="justify-self-center">
        <div class="flex justify-center border border-slate-400 p-7 rounded dark:border-slate-500">
            <button class="border border-slate-400" type="button" onclick={handleValidation}>
                Validate
            </button>
        </div>
        {#key validating}
            <FormulusColumn {validating}>
                <div></div>
            </FormulusColumn>
        {/key}
    </div>
</div>
